---
- hosts: all
  become: yes
  vars_files:
   - vars/main.yml

  roles:
    - idb
    - mysql
    - slapd
      #when: ldap_local
    - passenger
    - sidekiq
    - rake

  handlers:
    - include: handlers/main.yml
...
