---
- name: Create the IDB database
  mysql_db:
   name: idb
   state: present
- name: Create IDB MySQL user
  mysql_user:
   name: idb
   password: "{{ idb_mysql_password }}"
   priv: 'idb.*:ALL'
   state: present
- name: Adjust MySQL user settings in IDB config
  lineinfile:
    dest: "/opt/the-idb/config/database.yml"
    regexp: "password"
    line: "  password: {{ idb_mysql_password }}"
    state: present

