---
- name: Install some needed packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - redis-server
      - git
  when: ansible_os_family == "Debian"

- name: Install some needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - redis
      - git
  when: ansible_os_family == "RedHat"

- include: apt.yml
  when:
    - ansible_os_family == "Debian"
    - use_repo

- include: git.yml
  when: use_repo == false

- include: rvm.yml
  when: use_repo == false

# not supported ATM
#
#- include: yum.yml
#  when:
#    - ansible_os_family == "RedHat"
#    - use_repo
