- name: Install MySQL community repo
  yum:
     name: "https://dev.mysql.com/get/mysql57-community-release-el{{ansible_distribution_major_version}}-11.noarch.rpm"
     state: present

- name: Install MySQL server
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - python-ldap
   - mysql-community-server
   - mysql-community-devel
   - MySQL-python
